"use client";

import { useEffect, useState, useMemo } from "react";
import { 
  PlusCircle, 
  MinusCircle, 
  Trash2, 
  ShoppingBag, 
  User, 
  Phone, 
  CreditCard, 
  Banknote,
  Search,
  CheckCircle2,
  XCircle,
  Clock
} from "lucide-react";
import { useMenuStore } from "@/store/useMenuStore";
import { useCartStore } from "@/store/useCartStore";
import { useOrdersStore } from "@/store/useOrdersStore";
import { useToastStore } from "@/store/useToastStore";
import { useDynamicPricing } from "@/hooks/useDynamicPricing";
import { pb } from "@/lib/pocketbase";
import { Table } from "@rms/types";

export default function CheckoutPage() {
  const { categories, items: allMenuItems, fetchMenuItems, isLoading: menuLoading } = useMenuStore();
  const { 
    items: cartItems, 
    addToCart, 
    removeFromCart, 
    updateQuantity, 
    clearCart,
    customerName,
    customerPhone,
    paymentMethod,
    setCustomer,
    setPaymentMethod,
    getTotal,
    orderType,
    setOrderType,
    customerAddress,
    toggleBread,
    toggleCutlery,
    wantsBread,
    wantsCutlery
  } = useCartStore();
  const { fetchOrders } = useOrdersStore();

  const [activeCategory, setActiveCategory] = useState<string | null>("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [tables, setTables] = useState<Table[]>([]);
  const [selectedTableId, setSelectedTableId] = useState<string | null>(null);

  const { getDynamicPrice, isPeakTime, isEnabled } = useDynamicPricing();

  useEffect(() => {
    import('@/lib/repositories/TablesRepository').then(async mod => {
      const isTauri = typeof window !== 'undefined' && (window as any).__TAURI_INTERNALS__;
      
      let data = [];
      if (isTauri) {
        const { LocalTablesRepository } = await import('@/lib/repositories/localTables');
        data = await LocalTablesRepository.fetchAll();
      } else {
        data = await mod.TablesRepository.fetchAll();
      }
      
      setTables(data.filter(t => t.isActive));
    });
  }, []);

  useEffect(() => {
    fetchMenuItems();
    useMenuStore.getState().fetchCategories();
  }, [fetchMenuItems]);

  const filteredItems = useMemo(() => {
    let items = allMenuItems;
    if (activeCategory && activeCategory !== 'all') {
      items = items.filter(i => i.categoryId === activeCategory);
    }
    if (searchQuery) {
      items = allMenuItems.filter(i => i.name.toLowerCase().includes(searchQuery.toLowerCase()));
    }
    return items.filter(i => i.isActive);
  }, [allMenuItems, activeCategory, searchQuery]);

  const handleCreateOrder = async () => {
    if (cartItems.length === 0) return;
    setIsSubmitting(true);
    
    try {
      const { OrdersRepository } = await import('@/lib/repositories/orders');
      
      // Use reactive variable or direct getState for handlers is fine, but since we extracted them:
      let extendedCustomerName = customerName || "Гость";
      const typeStr = orderType === 'delivery' ? 'Доставка' : orderType === 'pickup' ? 'Самовывоз' : 'На месте';
      extendedCustomerName += ` [${typeStr}]`;
      
      if (orderType === 'delivery' && customerAddress) {
        extendedCustomerName += ` (Адрес: ${customerAddress})`;
      }
      
      const extras = [];
      if (wantsBread) extras.push("Хлеб");
      if (wantsCutlery) extras.push("Приборы");
      if (extras.length > 0) {
        extendedCustomerName += ` | ${extras.join(', ')}`;
      }

      if (orderType === 'dine_in' && selectedTableId) {
        const table = tables.find(t => t.id === selectedTableId);
        if (table) {
          extendedCustomerName += ` (Стол: ${table.number})`;
        }
      }

      const orderRecord = await OrdersRepository.create({
        customerName: extendedCustomerName,
        customerPhone: customerPhone || "",
        status: "new",
        totalAmount: getTotal(),
        paymentMethod: paymentMethod,
        tableId: orderType === 'dine_in' && selectedTableId ? selectedTableId : undefined,
      });

      // Create order items
      for (const item of cartItems) {
        await OrdersRepository.createItem(orderRecord.id, {
          id: '', // temporary, will be generated by PB
          menuItemName: item.name,
          quantity: item.quantity,
          priceAtTime: item.price,
          menuItemId: item.menuItemId
        });
      }

      clearCart();
      fetchOrders();
      useToastStore.getState().success("Заказ успешно создан!");
      clearCart();
    } catch (err: any) {
      useToastStore.getState().error("Ошибка при создании заказа: " + err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="flex h-[calc(100vh-120px)] gap-6 overflow-hidden">
      {/* Left Column: Menu Items */}
      <div className="flex-1 flex flex-col gap-6 overflow-hidden">
        <div className="flex items-center justify-between">
          <div className="flex items-baseline gap-4">
            <h1 className="text-3xl font-bold tracking-tight">Касса</h1>
            {isEnabled && isPeakTime && (
              <div className="flex items-center gap-1.5 px-3 py-1 bg-orange-500/10 border border-orange-500/20 rounded-full animate-pulse">
                <Clock className="w-3.5 h-3.5 text-orange-500" />
                <span className="text-[10px] font-black text-orange-500 uppercase tracking-tighter">Peak Pricing Active</span>
              </div>
            )}
          </div>
          <div className="relative w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input 
              type="text" 
              placeholder="Поиск блюд..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-[#141414] border border-white/5 rounded-xl py-2 pl-10 pr-4 text-sm focus:outline-none focus:border-orange-500/50 transition-colors"
            />
          </div>
        </div>

        {/* Categories */}
        <div className="flex gap-2 pb-2 overflow-x-auto custom-scrollbar">
          <button
            onClick={() => {
              setActiveCategory('all');
              setSearchQuery("");
            }}
            className={`px-4 py-2 rounded-xl text-sm font-medium transition-colors whitespace-nowrap border ${
              activeCategory === 'all' 
                ? 'bg-orange-500 text-white border-orange-500 shadow-lg shadow-orange-500/20' 
                : 'bg-[#141414] text-neutral-400 border-white/5 hover:text-white hover:bg-white/5'
            }`}
          >
            Все
          </button>
          {categories.map(cat => (
            <button
              key={cat.id}
              onClick={() => {
                setActiveCategory(cat.id);
                setSearchQuery("");
              }}
              className={`px-4 py-2 rounded-xl text-sm font-medium transition-colors whitespace-nowrap border ${
                activeCategory === cat.id 
                  ? 'bg-orange-500 text-white border-orange-500 shadow-lg shadow-orange-500/20' 
                  : 'bg-[#141414] text-neutral-400 border-white/5 hover:text-white hover:bg-white/5'
              }`}
            >
              {cat.name}
            </button>
          ))}
        </div>

        {/* Grid of Items */}
        <div className="flex-1 overflow-y-auto custom-scrollbar pr-2">
          {menuLoading ? (
            <div className="flex items-center justify-center h-full">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-orange-500"></div>
            </div>
          ) : filteredItems.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-neutral-500 gap-4">
              <ShoppingBag className="w-12 h-12 opacity-20" />
              <p>Ничего не найдено</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              {filteredItems.map(item => {
                const dynamicPrice = getDynamicPrice(item.price);
                const hasMarkup = dynamicPrice > item.price;
                
                return (
                  <button
                    key={item.id}
                    onClick={() => addToCart({ 
                      id: item.id, 
                      name: item.name, 
                      price: dynamicPrice, 
                      menuItemId: item.id 
                    })}
                    className="bg-[#141414] border border-white/5 rounded-2xl p-4 flex flex-col items-start text-left hover:border-orange-500/30 transition-all group active:scale-[0.98] relative overflow-hidden"
                  >
                    <div className="w-full aspect-square bg-white/5 rounded-xl mb-3 overflow-hidden">
                      {item.image ? (
                        <img src={item.image} alt={item.name} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center text-neutral-700 font-bold text-2xl uppercase">
                          {item.name.charAt(0)}
                        </div>
                      )}
                    </div>
                    <h3 className="font-bold text-sm line-clamp-2 mb-1 group-hover:text-orange-500 transition-colors uppercase tracking-tight">{item.name}</h3>
                    <div className="flex items-center gap-2">
                      <p className={`font-black ${hasMarkup ? 'text-orange-500' : 'text-white'}`}>
                        {dynamicPrice} ₪
                      </p>
                      {hasMarkup && (
                        <span className="text-[10px] text-neutral-500 line-through font-medium">
                          {item.price}
                        </span>
                      )}
                    </div>
                    {hasMarkup && (
                      <div className="absolute top-2 right-2 bg-orange-500 text-white text-[8px] font-black px-1.5 py-0.5 rounded-full shadow-lg">
                        🔥 ПИК
                      </div>
                    )}
                  </button>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Right Column: Cart */}
      <div className="w-96 bg-[#141414] border border-white/5 rounded-3xl flex flex-col overflow-hidden shadow-2xl">
        <div className="p-4 border-b border-white/5 bg-white/2 flex items-center justify-between">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <ShoppingBag className="w-5 h-5 text-orange-500" /> Корзина
          </h2>
          {cartItems.length > 0 && (
            <button 
              onClick={clearCart}
              className="text-xs text-red-500 hover:text-red-400 font-medium transition-colors"
            >
              Очистить
            </button>
          )}
        </div>

        {/* Cart Items Area */}
        <div className="flex-none max-h-[30vh] overflow-y-auto p-4 space-y-3 custom-scrollbar border-b border-white/5">
          {cartItems.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-neutral-600 gap-4 opacity-50 py-8">
              <div className="w-12 h-12 rounded-full border-2 border-dashed border-current flex items-center justify-center">
                <PlusCircle className="w-6 h-6" />
              </div>
              <p className="text-sm">Выберите блюда в меню</p>
            </div>
          ) : (
            cartItems.map(item => (
              <div key={item.id} className="flex gap-2 bg-white/2 p-2 rounded-xl border border-white/5 animate-in slide-in-from-right-4">
                <div className="flex-1">
                  <h4 className="text-sm font-bold truncate">{item.name}</h4>
                  <p className="text-xs text-orange-500 font-bold mt-1">{item.price} ₪ × {item.quantity}</p>
                </div>
                <div className="flex items-center gap-2 bg-black/20 rounded-lg px-2 text-sm">
                  <button onClick={() => updateQuantity(item.id, -1)} className="p-1 hover:text-orange-500 transition-colors">
                    <MinusCircle className="w-3 h-3" />
                  </button>
                  <span className="font-bold min-w-[20px] text-center">{item.quantity}</span>
                  <button onClick={() => updateQuantity(item.id, 1)} className="p-1 hover:text-orange-500 transition-colors">
                    <PlusCircle className="w-3 h-3" />
                  </button>
                </div>
                <button onClick={() => removeFromCart(item.id)} className="p-2 text-neutral-600 hover:text-red-500 transition-colors">
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            ))
          )}
        </div>

        {/* Client Config Area */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar bg-white/2">
          
          {/* Order Types */}
          <div className="flex gap-1 bg-black/20 p-1 rounded-xl">
            {(['dine_in', 'pickup', 'delivery'] as const).map(type => (
              <button
                key={type}
                onClick={() => setOrderType(type)}
                className={`flex-1 py-1.5 text-xs font-bold rounded-lg transition-colors ${
                  orderType === type
                    ? 'bg-orange-500 text-white shadow-md'
                    : 'text-neutral-500 hover:bg-white/5 hover:text-white'
                }`}
              >
                {type === 'dine_in' ? 'В зале' : type === 'pickup' ? 'Самовывоз' : 'Доставка'}
              </button>
            ))}
          </div>

          <div className="space-y-2">
            <div className="relative">
              <User className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input 
                type="text" 
                placeholder="Имя клиента" 
                value={customerName}
                onChange={(e) => setCustomer(e.target.value, customerPhone, customerAddress)}
                className="w-full bg-black/40 border border-white/5 rounded-xl py-2 pl-10 pr-4 text-sm focus:outline-none focus:border-orange-500/50 transition-colors"
              />
            </div>
            <div className="relative">
              <Phone className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input 
                type="text" 
                placeholder="Телефон" 
                value={customerPhone}
                onChange={(e) => setCustomer(customerName, e.target.value, customerAddress)}
                className="w-full bg-black/40 border border-white/5 rounded-xl py-2 pl-10 pr-4 text-sm focus:outline-none focus:border-orange-500/50 transition-colors"
              />
            </div>
            
            {orderType === 'delivery' && (
              <div className="relative animate-in fade-in slide-in-from-top-2">
                <input 
                  type="text" 
                  placeholder="Адрес доставки..." 
                  value={customerAddress}
                  onChange={(e) => setCustomer(customerName, customerPhone, e.target.value)}
                  className="w-full bg-orange-500/10 border border-orange-500/30 rounded-xl py-2 px-4 text-sm focus:outline-none focus:border-orange-500 transition-colors placeholder:text-orange-500/40 text-orange-100"
                />
              </div>
            )}

            {orderType === 'dine_in' && (
              <div className="relative animate-in fade-in slide-in-from-top-2">
                <select
                  value={selectedTableId || ""}
                  onChange={(e) => setSelectedTableId(e.target.value)}
                  className="w-full bg-[#141414] border border-white/5 rounded-xl py-2 px-4 text-sm focus:outline-none focus:border-orange-500 transition-colors text-white appearance-none"
                >
                  <option value="" disabled>
                    {tables.length === 0 ? "⚠️ Сначала создайте столы в меню Зал" : "Выберите стол..."}
                  </option>
                  {tables.map(t => (
                    <option key={t.id} value={t.id}>
                      Стол №{t.number} ({t.seats} мест) {/* t.zone && `- ${t.zone}` */}
                    </option>
                  ))}
                </select>
              </div>
            )}
          </div>

          {/* Bread and Cutlery */}
          <div className="flex gap-2">
            <button
              onClick={() => toggleBread()}
              className={`flex-1 py-2 rounded-xl text-xs font-bold border transition-all ${
                wantsBread 
                  ? 'bg-amber-500 border-amber-500 text-white' 
                  : 'bg-black/20 border-white/5 text-neutral-400 hover:text-white hover:bg-white/5'
              }`}
            >
              Хлеб
            </button>
            <button
              onClick={() => toggleCutlery()}
              className={`flex-1 py-2 rounded-xl text-xs font-bold border transition-all ${
                wantsCutlery 
                  ? 'bg-amber-500 border-amber-500 text-white' 
                  : 'bg-black/20 border-white/5 text-neutral-400 hover:text-white hover:bg-white/5'
              }`}
            >
              Приборы
            </button>
          </div>
        </div>

        {/* Footer: Summary and Pay */}
        <div className="p-4 bg-[#141414] border-t border-white/5 space-y-3 z-10 shadow-[0_-10px_20px_rgba(0,0,0,0.2)]">
          <div className="flex gap-2">
            <button 
              onClick={() => setPaymentMethod('cash')}
              className={`flex-1 flex flex-col items-center justify-center gap-1 py-2 rounded-xl border transition-all ${
                paymentMethod === 'cash' 
                  ? 'bg-orange-500/10 border-orange-500 text-orange-500 shadow-lg shadow-orange-500/10' 
                  : 'bg-black/20 border-white/5 text-neutral-400 hover:bg-white/5'
              }`}
            >
              <Banknote className="w-4 h-4" />
              <span className="text-[9px] font-bold uppercase">Наличные</span>
            </button>
            <button 
              onClick={() => setPaymentMethod('bit')}
              className={`flex-1 flex flex-col items-center justify-center gap-1 py-2 rounded-xl border transition-all ${
                paymentMethod === 'bit' 
                  ? 'bg-purple-500/10 border-purple-500 text-purple-500 shadow-lg shadow-purple-500/10' 
                  : 'bg-black/20 border-white/5 text-neutral-400 hover:bg-white/5'
              }`}
            >
              <CreditCard className="w-4 h-4" />
              <span className="text-[9px] font-bold uppercase">Bit / Карта</span>
            </button>
          </div>

          <div className="flex items-center justify-between py-1 border-y border-white/5">
            <span className="text-xs font-medium text-neutral-400 uppercase tracking-wider">Итого</span>
            <span className="text-2xl font-black text-white">{getTotal().toFixed(2)} ₪</span>
          </div>

          <button 
            disabled={cartItems.length === 0 || isSubmitting}
            onClick={handleCreateOrder}
            className="w-full bg-orange-500 hover:bg-orange-600 disabled:bg-neutral-800 disabled:text-neutral-500 text-white font-black py-3 rounded-xl shadow-xl shadow-orange-500/20 active:scale-[0.99] transition-all flex items-center justify-center gap-2 group"
          >
            {isSubmitting ? (
              <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
            ) : (
              <>
                <ShoppingBag className="w-5 h-5 group-hover:scale-110 transition-transform" />
                ОФОРМИТЬ ЗАКАЗ
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
