# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import morphs_pb2 as morphs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in morphs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MlWorkerStub(object):
    """Мозг на Rust обращается к Worker-у на Python
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunInference = channel.unary_unary(
                '/morphs.MlWorker/RunInference',
                request_serializer=morphs__pb2.InferenceRequest.SerializeToString,
                response_deserializer=morphs__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.ReportReward = channel.unary_unary(
                '/morphs.MlWorker/ReportReward',
                request_serializer=morphs__pb2.RewardMetric.SerializeToString,
                response_deserializer=morphs__pb2.AckResponse.FromString,
                _registered_method=True)


class MlWorkerServicer(object):
    """Мозг на Rust обращается к Worker-у на Python
    """

    def RunInference(self, request, context):
        """Выполнить MLX-инференс
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportReward(self, request, context):
        """Atropos: Отправить метрики RL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MlWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInference,
                    request_deserializer=morphs__pb2.InferenceRequest.FromString,
                    response_serializer=morphs__pb2.InferenceResponse.SerializeToString,
            ),
            'ReportReward': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportReward,
                    request_deserializer=morphs__pb2.RewardMetric.FromString,
                    response_serializer=morphs__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morphs.MlWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('morphs.MlWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MlWorker(object):
    """Мозг на Rust обращается к Worker-у на Python
    """

    @staticmethod
    def RunInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/morphs.MlWorker/RunInference',
            morphs__pb2.InferenceRequest.SerializeToString,
            morphs__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/morphs.MlWorker/ReportReward',
            morphs__pb2.RewardMetric.SerializeToString,
            morphs__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
