# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: morphs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'morphs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmorphs.proto\x12\x06morphs\"I\n\x10InferenceRequest\x12\x10\n\x08morph_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"M\n\x11InferenceResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\"Q\n\x0cRewardMetric\x12\x1f\n\x17\x65xecution_trajectory_id\x18\x01 \x01(\t\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x10\n\x08metadata\x18\x03 \x01(\t\"\x1f\n\x0b\x41\x63kResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x8a\x01\n\x08MlWorker\x12\x43\n\x0cRunInference\x12\x18.morphs.InferenceRequest\x1a\x19.morphs.InferenceResponse\x12\x39\n\x0cReportReward\x12\x14.morphs.RewardMetric\x1a\x13.morphs.AckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'morphs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=24
  _globals['_INFERENCEREQUEST']._serialized_end=97
  _globals['_INFERENCERESPONSE']._serialized_start=99
  _globals['_INFERENCERESPONSE']._serialized_end=176
  _globals['_REWARDMETRIC']._serialized_start=178
  _globals['_REWARDMETRIC']._serialized_end=259
  _globals['_ACKRESPONSE']._serialized_start=261
  _globals['_ACKRESPONSE']._serialized_end=292
  _globals['_MLWORKER']._serialized_start=295
  _globals['_MLWORKER']._serialized_end=433
# @@protoc_insertion_point(module_scope)
