version: '3.8'
services:
  borsch-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: borsch_v2
    ports:
      - "5432:5432"
    volumes:
      - borsch_pgdata:/var/lib/postgresql/data

volumes:
  borsch_pgdata:
