const fs = require('fs');
const path = require('path');

function walk(dir) {
    let results = [];
    const list = fs.readdirSync(dir);
    list.forEach(file => {
        file = path.join(dir, file);
        const stat = fs.statSync(file);
        if (stat && stat.isDirectory()) {
            results = results.concat(walk(file));
        } else if (file.endsWith('.test.ts') || file.endsWith('.test.tsx')) {
            results.push(file);
        }
    });
    return results;
}

const files = walk(path.join(process.cwd(), 'apps/backoffice/src/store/__tests__'));

files.forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    
    // Fix setState arguments
    content = content.replace(/setState\(initialState, true\)/g, 'setState(initialState)');
    
    // Fix garbage arguments
    content = content.replace(/\({} as any, {} as any, {} as any\)/g, '()');
    
    // Fix store.if -> delete the whole block
    content = content.replace(/if\s*\(typeof\s*store\.if\s*===\s*'function'\)\s*\{[\s\S]*?\}\s*catch[^\}]+\}/g, '');
    content = content.replace(/if\s*\(typeof\s*store\.for\s*===\s*'function'\)\s*\{[\s\S]*?\}\s*catch[^\}]+\}/g, '');
    
    // Fallback for store.if just in case
    content = content.replace(/store\.if\(\)/g, '');
    content = content.replace(/store\.for\(\)/g, '');

    fs.writeFileSync(file, content);
});
console.log('Fixed autogenerated tests.');
